# controllerType -- Wether to setup a daemonset or a deployment for the Scalyr agent
# A daemonset should be used for Kubernetes monitoring while a deployment should be used for single resource
# monitorings (e.g. hosted databases, etc.)
# Valid values: "daemonset" or "deployment"
controllerType: "daemonset"

deployment:
  # deployment.replicaCount -- The count of replicas to use when using the deployment controller setup
  replicaCount: 1

# volumes -- Additional volumes to mount
volumes: {}

# volumeMounts -- Additional volume mounts to set up
volumeMounts: {}

scalyr:
  # scalyr.server -- The Scalyr server to send logs to
  server: "scalyr.com"
  # scalyr.apiKey -- The Scalyr API key to use
  apiKey: ""
  k8s:
    # scalyr.k8s.clusterName -- The kubernetes cluster name (when using the kubernetes monitoring)
    clusterName: ""
    # scalyr.k8s.verifyKubeletQueries -- Set this to true and set up scalyr.k8s.caCert to activate TLS validation
    # of queries to the k8s kubelet
    verifyKubeletQueries: "false"
    # scalyr.k8s.caCert -- The path to the CA certificate to use to verify TLS-connection to the kubelet
    caCert: ""
    # scalyr.k8s.enableLogs -- Enable fetching Pod/Container logs from Kubernetes
    enableLogs: true
    # scalyr.k8s.enableMetrics -- Enable fetching Kubernetes metrics. This requires scalyr.k8s.enableLogs to be true
    enableMetrics: true
    # scalyr.k8s.enableEvents -- Enable fetching Kubernetes events
    enableEvents: true
  # scalyr.config -- A hash of configuration files and their content as documented in the
  # [Scalyr agent configmap configuration documentation](https://app.scalyr.com/help/scalyr-agent-k8s#modify-config)
  config: {}
  # scalyr.base64Config -- As Helm is currently
  # [unable to correctly pass JSON strings](https://github.com/helm/helm/issues/5618), this can be set to true so
  # all values of scalyr.config are expected to be base64 encoded and will be decoded in the chart
  base64Config: true

image:
  # image.repository -- Image to use. Defaults to the official scalyr agent image
  repository: scalyr/scalyr-k8s-agent
  pullPolicy: IfNotPresent
  # image.tag -- Tag to use. Defaults to appVersion from the chart metadata
  tag: ""

# imagePullSecrets -- Image pull secrets to use if the image is in a private repository
imagePullSecrets: []
# nameOverride -- Override the default name that helm calculates
nameOverride: ""
# fullnameOverride -- Override the default full name that helm calculates
fullnameOverride: ""

# podAnnotations -- optional pod annotations
podAnnotations: {}

# podSercurityContext -- optional pod security context entries
podSecurityContext: {}

# securityContext -- optional security context entries
securityContext: {}

# resources -- Pod resources. Defaults to the values documented in the official
# [Installation guide](https://app.scalyr.com/help/install-agent-kubernetes)
resources:
  requests:
    cpu: "500m"
    memory: "500Mi"
  limits:
    cpu: "500m"
    memory: "500Mi"

# nodeSelector -- optional node selectors
nodeSelector: {}

# tolerations -- Pod tolerations. Defaults to the values documented in the official
# [Installation guide](https://app.scalyr.com/help/install-agent-kubernetes)
tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"

# affinity -- optional affinity rules
affinity: {}
