{{- if or (.Values.scalyr.k8s.enableMetrics) (.Values.scalyr.k8s.enableLogs) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "scalyr-helm.fullname" . }}-cluster-role
  labels:
  {{- include "scalyr-helm.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - "namespaces"
      - "pods"
      - "replicationcontrollers"
    verbs:
      - "get"
      - "list"
  - apiGroups:
      - ""
    resources:
      - "nodes"
    verbs:
      - "get"
      - "list"
  - apiGroups:
      - "apps"
    resources:
      - "daemonsets"
      - "deployments"
      - "replicasets"
      - "statefulsets"
      - "namespaces"
    verbs:
      - "get"
      - "list"
  - apiGroups:
      - "batch"
      - "extensions"
    resources:
      - "cronjobs"
      - "jobs"
    verbs:
      - "get"
      - "list"
  - apiGroups:
      - ""
      - "events.k8s.io"
    resources:
      - "events"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - ""
    resources:
      - "nodes/stats"
    verbs:
      - "get"
{{- end }}
