apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scalyr-helm.fullname" . }}-config-agent-d
  labels:
  {{- include "scalyr-helm.labels" . | nindent 4 }}
data:
  {{- if or (.Values.scalyr.k8s.enableEvents) (.Values.scalyr.k8s.enableLogs) }}
  "kubernetes.json": |
    {
      "monitors":[
        {{- if .Values.scalyr.k8s.enableEvents }}
        {
          "module": "scalyr_agent.builtin_monitors.kubernetes_events_monitor"
        }{{- if .Values.scalyr.k8s.enableLogs }},{{- end }}
        {{- end }}
        {{- if .Values.scalyr.k8s.enableLogs }}
        {
          "module": "scalyr_agent.builtin_monitors.kubernetes_monitor",
          "report_container_metrics": {{ .Values.scalyr.k8s.enableMetrics }},
          "report_k8s_metrics": {{ .Values.scalyr.k8s.enableMetrics }}
        }
        {{- end }}
      ]
    }
  {{- end }}
  {{- range $key, $value := .Values.scalyr.config }}
  "{{ $key }}": |
    {{ if $.Values.scalyr.base64Config }}{{ $value | b64dec }}{{ else }}{{ $value }}{{ end }}
  {{- end }}
