{{- if or (.Values.scalyr.k8s.enableMetrics) (.Values.scalyr.k8s.enableLogs) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "scalyr-helm.fullname" . }}-sa
  labels:
    {{- include "scalyr-helm.labels" . | nindent 4 }}
secrets:
  - name: "scalyr-api-key"
automountServiceAccountToken: true
{{- end }}
